// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qckzeclvubsiyypmkatr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFja3plY2x2dWJzaXl5cG1rYXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzOTk2MjQsImV4cCI6MjA1Mzk3NTYyNH0.AYCX7XbtcwctoA6Ef5dVyVZRidBPovVI5gptpDMhVUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);